language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install -r requirements.txt
script: pytest
env:
  global:
  - secure: JDuTSwZVpATLQPX8b30bz9Blwzd1YAitNXaxOsFOGdjuq6SpDckuqq2rD+9b/ftc4xltXxToXALhvf63VTBMTI0axKoWQjK0XRQwdV2JUSvoJ1lbHtWOx1fS6rtSJMQ5Vd6wSWKI2Z23pt8SUqlLrGyqi4zFMOk6w3Ym1RUA52o=
  - secure: Rc0U3xOEWShamwCxQTjrrD4dkcTMJ7FnbTHmjnmQUs3a4xIrGioe6jwjaBc+ifSTys2I9U8eOsPrMudswDtwCBA1gOS1X/Z/qYHd2P+JHraajKaxipA0ZGB3akwx9aSX5s85my+2zTXobjbFhMXUKKnK2Cwb0dXl300oFMkC/Nw=
  - secure: Khv8vi+PHpST07nyE1LqkLMYNYQshCpbeTonpdmm+SvW4DSoVKMKytww0w4vcmCbIDKw6iAWkKFQMi2KeWqFfZMnj6M4Q0FY3R6KnZlSHJsA1YItkQ2g9eJTIZZlumdevpPGQAKTEB0JreFRbe0UPoKJ5tJfd8rd0c9UF4jXiIY=
